function main()

    println(false || true)
    println(true || false)
    println(false || true || true)
    println(false || false)
    println(false || true || false)
    println(true && false || true)
    println(true && false || true)
    println(false && true)
    println(true && false)
    println(false && false)
    println("Bool comparison")
    println(false == false)
    println(true == true)
    println(false == true)
    println(true == false)
    println("String comparison")
    println("abc" == "abc")
    println("abc" != "abC")
    println("abc" == "ab")
    println("abc" != "abc")
    println("Equality")
    println(1 == 1)
    println(1.5 == 1.5)
    println(1.0 == 1)
    println(1 == 1.0)
    println(1 == 2)
    println(2 == 1)
    println(1.1 == 1.0)
    println(1.0 == 1.1)
    println(1.1 == 1)
    println(1 == 1.1)
    println("Inequality")
    println(1 != 2)
    println(2 != 1)
    println(1.1 != 1.0)
    println(1.0 != 1.1)
    println(1.1 != 1)
    println(1 != 1.1)
    println(1 != 1)
    println(1.5 != 1.5)
    println(1.0 != 1)
    println(1 != 1.0)
    println("Greater")
    println(2 > 1)
    println(2.0 > 1)
    println(2 > 1.0)
    println(1 > 2)
    println(1.0 > 2)
    println(1 > 2.0)
    println("Smaller")
    println(1 < 2)
    println(1.0 < 2)
    println(1 < 2.0)
    println(2 < 1)
    println(2.0 < 1)
    println(2 < 1.0)
    println("Greaterequal")
    println(2 >= 1)
    println(2.0 >= 1)
    println(2 >= 1.0)
    println(1 >= 1)
    println(1.5 >= 1.5)
    println(1.1 >= 1.0)
    println(1.0 >= 1)
    println(1.1 >= 1)
    println(1 >= 1.0)
    println(1 >= 2)
    println(1.0 >= 2)
    println(1 >= 2.0)
    println(1.0 >= 2.0)
    println(1.0 >= 1.1)
    println(1 >= 1.1)
    println("Smallerequal")
    println(1 <= 2)
    println(1 <= 2.0)
    println(1.0 <= 2)
    println(1 <= 1)
    println(1.5 <= 1.5)
    println(1.0 <= 1.1)
    println(1 <= 1.0)
    println(1 <= 1.1)
    println(1.0 <= 1)
    println(2 <= 1)
    println(2 <= 1.0)
    println(2.0 <= 1)
    println(2.0 <= 1.0)
    println(1.1 <= 1.0)
    println(1.1 <= 1)

end
main()